consulclient:
  image: progrium/consul
  net: "host"
  privileged: true
  command:
    - -advertise ${SERVICE_IP} -join ${HANDSON_SERVER}
  container_name: consul
  hostname: ${HOSTNAME}
  restart: always
  volumes:
    - /etc/localtime:/etc/localtime:ro

registrator:
  image: gliderlabs/registrator:master
  hostname: ${HOSTNAME}
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - /etc/localtime:/etc/localtime:ro
  command: -ip ${SERVICE_IP} consul://${IP}:8500
  container_name: registrator
  restart: always
  net: "host"

